Controllers/Battleship/BattleshipController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using StraightLine.Models.Battleship;

namespace StraightLine.Controllers.Battleship
{
    public class BattleshipController : Controller
    {
        private static Stack<GameState> _gameStateStack;
        private static GameState _activeGameState;

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult StartedGame(string PlayerGuid)
        {

            return View();
        }

        [Route("api/Bomb/{position}")]
        [HttpPost]
        [AllowAnonymous]
        public IActionResult Bomb(string position)
        {
            var gameState = new GameState();

            return Ok(gameState);
        }

        [Route("api/PlaceShip/{position}/{horizontal}")]
        [HttpPost]
        [AllowAnonymous]
        public IActionResult PlaceShip(string position, bool horizontal)
        {
            return Ok();
        }

        [Route("api/Load")]
        [HttpGet]
        [AllowAnonymous]
        public IActionResult Load()
        {
            _activeGameState = null;
            if (_gameStateStack == null)
            { _gameStateStack = new Stack<GameState>(); }

            foreach (var gameState in _gameStateStack) // Find existing game, if any
            {
                if (HttpContext.Session.GetString("GameGUID") == gameState.GameGuid.ToString())
                { _activeGameState = gameState; }
            }

            if (_gameStateStack.Count != 0 && _gameStateStack.Peek().Player2 == null && _gameStateStack.Peek().Player1.PlayerGuid.ToString() != HttpContext.Session.GetString("PlayerGUID"))
            {
                _activeGameState = _gameStateStack.Peek();
                _activeGameState.Player2 = new Player();
                _activeGameState.Player2.GameGuid = _activeGameState.GameGuid;
                HttpContext.Session.SetString("PlayerGUID", _activeGameState.Player2.PlayerGuid.ToString());
            }
            else if (_activeGameState == null) // No existing game waiting on 2nd player
            {
                _activeGameState = new GameState();
                _activeGameState.Player1 = new Player();
                _activeGameState.Player1.GameGuid = _activeGameState.GameGuid;

                _gameStateStack.Push(_activeGameState);
                HttpContext.Session.SetString("PlayerGUID", _activeGameState.Player1.PlayerGuid.ToString());
            }

            HttpContext.Session.SetString("GameGUID", _activeGameState.GameGuid.ToString());

            if (HttpContext.Session.GetString("PlayerGUID") == _activeGameState.Player1.PlayerGuid.ToString())
            {
                return Ok(_activeGameState.Player1);
            }
            else if (HttpContext.Session.GetString("PlayerGUID") == _activeGameState.Player2.PlayerGuid.ToString())
            {
                return Ok(_activeGameState.Player2);
            }
            return BadRequest();
        }

        [Route("api/GetJsonForPlayer")]
        [HttpGet]
        [AllowAnonymous]
        public IActionResult GetJsonForPlayer(string PlayerGuid)
        {

            if (PlayerGuid == _activeGameState.Player1.PlayerGuid.ToString())
            {
                return Ok(_activeGameState.Player1);
            }
            else if (PlayerGuid == _activeGameState.Player2.PlayerGuid.ToString())
            {
                return Ok(_activeGameState.Player2);
            }
         
            return BadRequest();
        }

        [Route("api/GameStart/{PlayerGuid}")]
        [HttpPost]
        [AllowAnonymous]
        public IActionResult GameStart(string PlayerGuid)
        {
            if (PlayerGuid == _activeGameState.Player1.PlayerGuid.ToString())
            {
                _activeGameState.Player1.Ready = true;
            }
            else if (PlayerGuid == _activeGameState.Player2.PlayerGuid.ToString())
            {
                _activeGameState.Player2.Ready = true;
            }

            if (_activeGameState.Player2 == null)
            {
                return Ok(_activeGameState);
            }
            else if (_activeGameState.Player1.Ready == true && _activeGameState.Player2.Ready == true)
            {
                _activeGameState.BothPlayersReady = true;
                return Ok(_activeGameState.BothPlayersReady);
            }

                return Ok(_activeGameState);
        }

        [Route("api/Reset")]
        [HttpGet]
        [AllowAnonymous]
        public IActionResult Reset()
        {
            HttpContext.Session.Clear();
            return Ok();
        }
    }
}

Controllers/DragonSlayerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace StraightLine.Controllers
{
    public class DragonSlayerController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Test()
        {
            return View();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Straight_Line</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.3.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">MVC Home</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="http://tech-flex.com">Site Root</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    @*<li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>*@
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Projects
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a asp-area="" asp-controller="Battleship" asp-action="Index">Battleship</a></li>
                            <li><a asp-area="" asp-controller="DragonSlayer" asp-action="Index">Dragon Slayer</a></li>
                        </ul>
                    </li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2016 - Straight_Line</p>
        </footer>
    </div>

    @RenderSection("scripts", required: false)
</body>
</html>